REGISTER = 'REGISTER'
EXIT_NETWORK = 'EXIT_NETWORK'

REGISTER_ERROR = 'REGISTER_ERROR'
REGISTER_SUCCESS = 'REGISTER_SUCCESS'

LISTPEER = 'LISTPEER'

CHAT_REQUEST = 'CHAT_REQUEST'
CHAT_ACCEPT = 'CHAT_ACCEPT'
CHAT_REFUSE = 'CHAT_REFUSE'

CHAT_MESSAGE = 'CHAT_MESSAGE'
